---
- name: check zrepl command availability
  ansible.builtin.command:
    cmd: command -v zrepl
  register: __zrepl_cmd_output
  when: zfs_zrepl_enabled | bool
  changed_when: false

- name: fail when zrepl unavailable
  ansible.builtin.fail:
    msg: "zfs_zrepl_enabled is true but zrepl command is not available"
  when:
    - zfs_zrepl_enabled | bool
    - __zrepl_cmd_output.rc != 0

- name: configure zrepl
  ansible.builtin.template:
    src: etc/zrepl/zrepl.yml.j2
    dest: /etc/zrepl/zrepl.yml
    owner: root
    group: root
    mode: "0644"
    validate: zrepl configcheck --config %s
  notify: restart zrepl
  when: zfs_zrepl_enabled | bool
  vars:
    cfg: "{{ __zfs_zrepl_config_defaults | combine(zfs_zrepl_config, recursive=True) }}"
