---
# ------------------------------------------------------------------------------
# ZFS Installation
# ------------------------------------------------------------------------------

- name: Install ZFS (Alpine)
  community.general.apk:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - zfs

- name: ensure ZFS kernel module is loaded (Alpine)
  community.general.modprobe:
    name: zfs

- name: ensure ZFS kernel module is loaded in boot (Alpine)
  ansible.builtin.copy:
    content: zfs
    dest: /etc/modules-load.d/zfs.conf
    owner: root
    group: root
    mode: "0644"

# ------------------------------------------------------------------------------
# Zrepl Installation

# ZREPL package for Alpine is only available in Edge-Testing (2025-04-17),
# so for now I consider it unsupported. It still can be installed manually as binaries
# or from source and managed by this role
# ------------------------------------------------------------------------------


# - when: zfs_zrepl_enabled
#   block:
#     - when: zfs_manage_repository | bool
#       block:
#         - name: import zrepl repo GPG key (Debian)
#           ansible.builtin.apt_key:
#             data: "{{ lookup('file', 'debian/zrepl-apt-key.asc') }}"
#             id: E101418FD3D6FBCB9D65A62D708699FC5F2EBF16
#             state: present

#         - name: add zrepl repository (Debian)
#           ansible.builtin.apt_repository:
#             filename: zrepl
#             repo: >-
#               deb [arch=amd64] {{ zfs_zrepl_debian_repo_url }}/{{ ansible_distribution | lower }}
#               {{ ansible_distribution_release | lower }}
#               main
#             state: present

#     - name: install zrepl (Debian)
#       ansible.builtin.apt:
#         name: zrepl
#         state: present
